### PR TITLE
add michael-chiu to stakeholders

### PR DESCRIPTION
**Pull request by michael-yuji**
I work on a chain of projects
[XThread] Simple threading library to manage threads
[spartanX] socket framework using kqueue/epoll on multiple thread
[SXF97] HTTP parser
[CoreCache] Caching
[SML] Type safe HTML generation
[CKit] C API helper 
[swiftTLS] libressl wrapper

### CODE REVIEW

**Comment by paulofaria** [comment]
Can you please put your name following ascending alphabetical order?

**Comment by michael-yuji** [comment]
Oops, sorry I didn't realize it is sorted by first name. Fixed.

**Comment by seabaylea** [comment]
Sorry, we've now got merge conflicts that I can't fix on merge. Can you clean up?

**Comment by seabaylea** [comment]
Merging.

**Pull request merged**
