### PR TITLE
Make GitHub names clickable

### PR DESCRIPTION
**Pull request by BasThomas**
... so they redirect to the person's GitHub profile page.

### CODE REVIEW

**Comment by seabaylea** [comment]
@BasThomas It might be worth waiting on this as we're (hopefully) likely to get more stakeholders over the next few days, and then can update in bulk.

**Comment by ddunbar** [comment]
Of course then PRs will come in right form. :)

**Comment by BasThomas** [comment]
Seems like a good idea.

**Comment by seabaylea** [comment]
Ok - merging.

**Pull request merged**
